control_flow = "Visual"
function_arguments = "Visual"
function_calls = "Visual"
generics = "Visual"
where_predicates = "Visual"
control_brace_style = "ClosingNextLine"
fn_args_density = "Compressed"
format_macro_matchers = true
format_macro_bodies = true
imports_indent = "Visual"
merge_imports = true
merge_derives = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
reorder_modules = true
trailing_comma = "Never"
use_try_shorthand = true
max_width = 80
wrap_comments = true
