chain_split_single_child = true
max_width = 80
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
wrap_comments = true
fn_args_density = "Compressed"
trailing_comma = "Never"