[package]
name = "rustpager"
version = "0.3.1"
authors = ["Thomas Gatzweiler <mail@thomasgatzweiler.com>"]

[dependencies]
log = "^0.3"
serial = "^0.3"
ws = "^0.5.3"
tiny_http = "^0.5.7"
serde = "^0.8.21"
serde_derive = "^0.8.21"
serde_json = "^0.8.4"

[dependencies.raspi]
path = "lib/raspi"
