[package]
name = "rustpager"
version = "0.4.2"
authors = ["Thomas Gatzweiler <mail@thomasgatzweiler.com>"]

[dependencies]
log = "^0.3"
serial = "^0.3"
ws = "^0.6"
tiny_http = "^0.5.7"
serde = "^0.9"
serde_derive = "^0.9"
serde_json = "^0.9"
lazy_static = "^0.2.2"
net2 = "^0.2.26"

[dependencies.raspi]
path = "lib/raspi"

[package.metadata.deb]
maintainer = "RWTH Amateurfunkgruppe <rwth-afu@online.de>"
copyright = "2017, RWTH Amateurfunkgruppe <rwth-afu@online.de>"
license_file = ["LICENSE", "0"]
extended_description = """\
Universal POCSAG transmitter controller"""
depends = "$auto"
section = "hamradio"
priority = "optional"
assets = [
    ["target/release/rustpager", "usr/bin/", "755"]
]
