[package]
name = "unipager"
version = "0.7.1"
authors = ["Thomas Gatzweiler <mail@thomasgatzweiler.com>"]

[dependencies]
log = "^0.3"
serial = "^0.3"
ws = "^0.7"
tiny_http = "^0.5.7"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
lazy_static = "^0.2"

[dependencies.raspi]
path = "lib/raspi"
