[package]
name = "rust_pager"
version = "0.1.0"
authors = ["Thomas Gatzweiler <mail@thomasgatzweiler.com>"]

[dependencies]
sysfs_gpio = "^0.4"
toml = "^0.2.1"
log = "^0.3"
env_logger = "^0.3.5"
serial = "^0.3"
