name: Debian Package for ARM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run:  sudo apt-get install devscripts build-essential lintian pbuilder qemu-user-static qemu-system-arm debhelper
    - name: Build debian package
      env:
        OS: "raspbian"
        DIST: "buster"
        ARCH: "armhf"
      run: |
        pwd
        ls ./
        ls ../
        sudo cp UniPager/debian/pbuilderrc /root/.pbuilderrc
        wget http://archive.raspbian.org/raspbian/pool/main/r/raspbian-archive-keyring/raspbian-archive-keyring_20120528.2_all.deb
        sudo dpkg -i raspbian-archive-keyring_20120528.2_all.deb
        sudo mkdir -p /var/cache/pbuilder/raspbian-buster-armhf/aptcache/
        sudo pbuilder --create
        sudo pbuilder build *.dsc
        ls /var/cache/pbuilder/result/
