name: Debian Package for ARM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install pbuilder debootstrap devscripts debian-archive-keyring
    - name: Build debian package
      env:
        PBUILDERSATISFYDEPENDSCMD: "/usr/lib/pbuilder/pbuilder-satisfydepends-apt"
      run: |
        sudo pbuilder create --distribution squeeze --mirror http://ftp.us.debian.org/debian/ --debootstrapopts "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg"
        sudo cowbuilder --create
        sudo pbuilder build *.dsc
        ls /var/cache/pbuilder/result/
