name: Debian Package for ARM
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: [linux, ARM]
    steps:
    - name: Install dependencies
      run:  sudo apt-get install devscripts build-essential lintian debhelper dh-systemd libudev-dev
    - uses: actions/checkout@v2
    - name: Build debian package
      run: |
        debuild -i -us -uc -S --lintian-opts --profile debian
