name: Debian Package for ARM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install pbuilder debootstrap devscripts debian-archive-keyring qemu-user-static
    - name: Build debian package
      env:
        MIRRORSITE: "http://ftp.acc.umu.se/mirror/raspbian/raspbian/"
        COMPONENTS: "main contrib non-free"
        DEBOOTSTRAPOPTS: "--arch armhf --keyring=/usr/share/keyrings/raspbian-archive-keyring.gpg"
        ARCH: "armhf"
        DIST: "buster"
      run: |
        wget http://archive.raspbian.org/raspbian/pool/main/r/raspbian-archive-keyring/raspbian-archive-keyring_20120528.2_all.deb
        sudo dpkg -i raspbian-archive-keyring_20120528.2_all.deb
        sudo pbuilder create --distribution buster
        pdebuild
        ls /var/cache/pbuilder/result/
