name: Debian Package for ARM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install pbuilder debootstrap devscripts debian-archive-keyring qemu-user-static
    - name: Build debian package
      run: |
        wget http://archive.raspbian.org/raspbian/pool/main/r/raspbian-archive-keyring/raspbian-archive-keyring_20120528.2_all.deb
        sudo dpkg -i raspbian-archive-keyring_20120528.2_all.deb
        sudo pbuilder create --architecture armhf --distribution buster --mirror "http://ftp.acc.umu.se/mirror/raspbian/raspbian/" --components "main contrib non-free" --debootstrapopts "--arch armhf --keyring=/usr/share/keyrings/raspbian-archive-keyring.gpg"  
        pdebuild
        ls /var/cache/pbuilder/result/
